### ISSUE TITLE
Repository License

### ISSUE THREAD

**Issue by jasonmhead** [johnbumgarner/synonyms_nlp#1]
Could this repository get a MIT license?

**Comment by johnbumgarner** [comment]
Why does this repository need a MIT license?  It only contains my research on this specific issue prior to me releasing [WordHoard.](https://github.com/johnbumgarner/wordhoard) under a MIT license.  A new version of that package is being released this week.

**Comment by jasonmhead** [comment]
Wasn't aware of WordHord - thank you

**Comment by johnbumgarner** [comment]
No worries.  Let me know how you like [WordHoard](https://github.com/johnbumgarner/wordhoard).  I'm always open to improving it for others to use.
